# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmPop(object):
    def setupUi(self, ConfirmPop):
        ConfirmPop.setObjectName("ConfirmPop")
        ConfirmPop.resize(341, 213)
        font = QtGui.QFont()
        font.setPointSize(16)
        ConfirmPop.setFont(font)
        self.title_lb = QtWidgets.QLabel(ConfirmPop)
        self.title_lb.setGeometry(QtCore.QRect(40, 30, 261, 51))
        self.title_lb.setObjectName("title_lb")
        self.yes_bt = QtWidgets.QPushButton(ConfirmPop)
        self.yes_bt.setGeometry(QtCore.QRect(60, 130, 81, 41))
        self.yes_bt.setObjectName("yes_bt")
        self.no_bt = QtWidgets.QPushButton(ConfirmPop)
        self.no_bt.setGeometry(QtCore.QRect(180, 130, 81, 41))
        self.no_bt.setObjectName("no_bt")

        self.retranslateUi(ConfirmPop)
        QtCore.QMetaObject.connectSlotsByName(ConfirmPop)

    def retranslateUi(self, ConfirmPop):
        _translate = QtCore.QCoreApplication.translate
        ConfirmPop.setWindowTitle(_translate("ConfirmPop", "提示"))
        self.title_lb.setText(_translate("ConfirmPop", "您确定要导出订单吗？"))
        self.yes_bt.setText(_translate("ConfirmPop", "确定"))
        self.no_bt.setText(_translate("ConfirmPop", "取消"))
