# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Form(object):
    def setupUi(self, Login_Form):
        Login_Form.setObjectName("Login_Form")
        Login_Form.resize(800, 500)
        self.pushButton = QtWidgets.QPushButton(Login_Form)
        self.pushButton.setGeometry(QtCore.QRect(350, 300, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.username_lb = QtWidgets.QLabel(Login_Form)
        self.username_lb.setGeometry(QtCore.QRect(260, 115, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_lb.setFont(font)
        self.username_lb.setObjectName("username_lb")
        self.password_lb = QtWidgets.QLabel(Login_Form)
        self.password_lb.setGeometry(QtCore.QRect(260, 205, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_lb.setFont(font)
        self.password_lb.setObjectName("password_lb")
        self.username_et = QtWidgets.QLineEdit(Login_Form)
        self.username_et.setGeometry(QtCore.QRect(330, 110, 181, 31))
        self.username_et.setObjectName("username_et")
        self.password_et = QtWidgets.QLineEdit(Login_Form)
        self.password_et.setGeometry(QtCore.QRect(330, 200, 181, 31))
        self.password_et.setObjectName("password_et")
        self.title_lb = QtWidgets.QLabel(Login_Form)
        self.title_lb.setGeometry(QtCore.QRect(340, 10, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title_lb.setFont(font)
        self.title_lb.setTextFormat(QtCore.Qt.AutoText)
        self.title_lb.setObjectName("title_lb")
        self.register_bt = QtWidgets.QPushButton(Login_Form)
        self.register_bt.setGeometry(QtCore.QRect(440, 260, 75, 24))
        self.register_bt.setObjectName("register_bt")

        self.retranslateUi(Login_Form)
        QtCore.QMetaObject.connectSlotsByName(Login_Form)

    def retranslateUi(self, Login_Form):
        _translate = QtCore.QCoreApplication.translate
        Login_Form.setWindowTitle(_translate("Login_Form", "系统登录"))
        self.pushButton.setText(_translate("Login_Form", "登录"))
        self.username_lb.setText(_translate("Login_Form", "用户名"))
        self.username_lb.adjustSize()
        self.password_lb.setText(_translate("Login_Form", "密码"))
        self.password_lb.adjustSize()
        self.title_lb.setText(_translate("Login_Form", "系统登录"))
        self.title_lb.adjustSize()
        self.register_bt.setText(_translate("Login_Form", "注册"))
        self.password_et.setEchoMode(QtWidgets.QLineEdit.Password)
