# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register_Form(object):
    def setupUi(self, Register_Form):
        Register_Form.setObjectName("Register_Form")
        Register_Form.resize(800, 500)
        self.register_bt = QtWidgets.QPushButton(Register_Form)
        self.register_bt.setGeometry(QtCore.QRect(340, 350, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.register_bt.setFont(font)
        self.register_bt.setObjectName("register_bt")
        self.username_lb = QtWidgets.QLabel(Register_Form)
        self.username_lb.setGeometry(QtCore.QRect(240, 130, 54, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_lb.setFont(font)
        self.username_lb.setObjectName("username_lb")
        self.password_lb = QtWidgets.QLabel(Register_Form)
        self.password_lb.setGeometry(QtCore.QRect(250, 180, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_lb.setFont(font)
        self.password_lb.setObjectName("password_lb")
        self.username_et = QtWidgets.QLineEdit(Register_Form)
        self.username_et.setGeometry(QtCore.QRect(330, 130, 181, 31))
        self.username_et.setObjectName("username_et")
        self.password_et = QtWidgets.QLineEdit(Register_Form)
        self.password_et.setGeometry(QtCore.QRect(330, 180, 181, 31))
        self.password_et.setObjectName("password_et")
        self.title_lb = QtWidgets.QLabel(Register_Form)
        self.title_lb.setGeometry(QtCore.QRect(340, 10, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title_lb.setFont(font)
        self.title_lb.setTextFormat(QtCore.Qt.AutoText)
        self.title_lb.setObjectName("title_lb")
        self.tel_lb = QtWidgets.QLabel(Register_Form)
        self.tel_lb.setGeometry(QtCore.QRect(243, 275, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tel_lb.setFont(font)
        self.tel_lb.setObjectName("tel_lb")
        self.tel_et = QtWidgets.QLineEdit(Register_Form)
        self.tel_et.setGeometry(QtCore.QRect(330, 270, 181, 31))
        self.tel_et.setObjectName("tel_et")
        self.psd2_lb = QtWidgets.QLabel(Register_Form)
        self.psd2_lb.setGeometry(QtCore.QRect(243, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.psd2_lb.setFont(font)
        self.psd2_lb.setObjectName("psd2_lb")
        self.password2_et = QtWidgets.QLineEdit(Register_Form)
        self.password2_et.setGeometry(QtCore.QRect(330, 220, 181, 31))
        self.password2_et.setObjectName("password2_et")

        self.retranslateUi(Register_Form)
        QtCore.QMetaObject.connectSlotsByName(Register_Form)

    def retranslateUi(self, Register_Form):
        _translate = QtCore.QCoreApplication.translate
        Register_Form.setWindowTitle(_translate("Register_Form", "系统注册"))
        self.register_bt.setText(_translate("Register_Form", "注册"))
        self.username_lb.setText(_translate("Register_Form", "用户名"))
        self.username_lb.adjustSize()
        self.password_lb.setText(_translate("Register_Form", "密码"))
        self.password_lb.adjustSize()
        self.title_lb.setText(_translate("Register_Form", "注册"))
        self.title_lb.adjustSize()
        self.tel_lb.setText(_translate("Register_Form", "手机号"))
        self.tel_lb.adjustSize()
        self.psd2_lb.setText(_translate("Register_Form", "确认密码"))
        self.psd2_lb.adjustSize()
        self.password_et.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password2_et.setEchoMode(QtWidgets.QLineEdit.Password)
