# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Form(object):
    def setupUi(self, Login_Form):
        Login_Form.setObjectName("Login_Form")
        Login_Form.resize(330, 298)
        self.pushButton = QtWidgets.QPushButton(Login_Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.username_lb = QtWidgets.QLabel(Login_Form)
        self.username_lb.setGeometry(QtCore.QRect(20, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_lb.setFont(font)
        self.username_lb.setObjectName("username_lb")
        self.password_lb = QtWidgets.QLabel(Login_Form)
        self.password_lb.setGeometry(QtCore.QRect(20, 150, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_lb.setFont(font)
        self.password_lb.setObjectName("password_lb")
        self.username_et = QtWidgets.QLineEdit(Login_Form)
        self.username_et.setGeometry(QtCore.QRect(90, 80, 191, 31))
        self.username_et.setObjectName("username_et")
        self.password_et = QtWidgets.QLineEdit(Login_Form)
        self.password_et.setGeometry(QtCore.QRect(90, 150, 191, 31))
        self.password_et.setInputMethodHints(QtCore.Qt.ImhNone)
        self.password_et.setObjectName("password_et")
        self.title_lb = QtWidgets.QLabel(Login_Form)
        self.title_lb.setGeometry(QtCore.QRect(110, 10, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_lb.setFont(font)
        self.title_lb.setTextFormat(QtCore.Qt.AutoText)
        self.title_lb.setObjectName("title_lb")

        self.retranslateUi(Login_Form)
        QtCore.QMetaObject.connectSlotsByName(Login_Form)

    def retranslateUi(self, Login_Form):
        _translate = QtCore.QCoreApplication.translate
        Login_Form.setWindowTitle(_translate("Login_Form", "系统登录"))
        self.pushButton.setText(_translate("Login_Form", "登录"))
        self.username_lb.setText(_translate("Login_Form", "用户名"))
        self.password_lb.setText(_translate("Login_Form", "密码"))
        self.title_lb.setText(_translate("Login_Form", "系统登录"))
